let a1 = 'hello';
let b1 = 'owu';
let c1 = 'com';
let d = 'ua';
let e = 1;
let f = 10;
let g = -999;
let h = 123;
let i = 3.14;
let j = 2.7;
let k = 16;
let l = true;
let m = false;
console.log(a1);
console.log(b1);
console.log(c1);
console.log(d);
console.log(e);
console.log(f);
console.log(g);
console.log(h);
console.log(i);
console.log(j);
console.log(k);
console.log(l);
console.log(m);
alert(a1);
alert(b1);
alert(c1);
alert(d);
alert(e);
alert(f);
alert(g);
alert(h);
alert(i);
alert(j);
alert(k);
alert(l);
alert(m);
document.write(a1);
document.write(b1);
document.write(c1);
document.write(d);
document.write(e);
document.write(f);
document.write(g);
document.write(h);
document.write(i);
document.write(j);
document.write(k);
document.write(l);
document.write(m);
let firstName = 'Карина';
let middleName = 'Віталіївна';
let lastName = 'Ловченко';
let person = firstName + middleName + lastName;
let a = 100;
let b = '100';
let c = true;
console.log(typeof a);
console.log(typeof b);
console.log(typeof c);
let firstname = prompt();
console.log(firstname);
let middlename = prompt();
console.log(middlename);
let age = prompt();
console.log(age);
